# -*- coding: utf-8 -*-
"""pipeline transformers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124mLG7T-dtv1zJqnuZM7-ezoxEpmb0Tm
"""

!pip install transformers -q

from transformers import pipeline

classifier = pipeline("sentiment-analysis")

result = classifier("I love learning AI!")
print(result)