# -*- coding: utf-8 -*-
"""Sentiment analysis model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cz9dQ_3DhOw_V15Rj0LF5vm1TnbQHJnY
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

# Load sentiment analysis model
sentiment = pipeline("sentiment-analysis")

# Load sentiment analysis model
sentiment = pipeline("sentiment-analysis")

# Sample product review (you can change this text)
review = """
The laptop starts quickly and works smoothly for daily tasks.
The screen quality is clear and good for watching videos.
Battery backup is average and needs charging often.
The fan makes noise when many apps are running.
Overall, it is a good laptop for students but not for gaming.
"""

# Split review into sentences
sentences = review.split(".")

pros = []
cons = []

for s in sentences:
    s = s.strip()
    if s == "":
        continue

    # Get sentiment result
    result = sentiment(s)[0]

    if result["label"] == "POSITIVE":
        pros.append(s)
    elif result["label"] == "NEGATIVE":
        cons.append(s)

# Take only first 2 pros and 2 cons
pros = pros[:2]
cons = cons[:2]

# Create DataFrame
df = pd.DataFrame({
    "Pros": pros,
    "Cons": cons
})

print(df)