# -*- coding: utf-8 -*-
"""SIMPLE LINE GRAPH

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iu6yRHRhHbX0jSC5kuj-zoO1o0c7MnsT
"""

import matplotlib.pyplot as plt

x = [1, 2, 3, 4]

y = [10, 20, 25, 30]

plt.plot(x, y)

plt.title("Simple Line Graph")
plt.xlabel("X Axis")
plt.ylabel("Y Axis")

plt.show()