# -*- coding: utf-8 -*-
"""Text generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cy4RoYkcTlBTgh6jbEx2pcGtr1vwLzXr
"""

!pip install transformers torch

from transformers import pipeline

# Load text generation model (GenAI)
generator = pipeline(
    "text-generation",
    model="gpt2"
)

# Input prompt
prompt = "Artificial Intelligence in finance will"

# Generate text
result = generator(prompt, max_length=50, num_return_sequences=1)

print("AI Generated Text:")
print(result[0]["generated_text"])