# -*- coding: utf-8 -*-
"""TIME TABLE GENERATOR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DxMnzOSmkYV8oVCA0isjI_R3bX8lDY-1
"""

import pandas as pd
import random

print("TIMETABLE GENERATOR\n")

# User Inputs
subjects_input = input("Enter subjects (comma separated): ")
days_input = input("Enter days (comma separated): ")
periods_per_day = int(input("Enter number of periods per day: "))

# Process Inputs
subjects = [s.strip() for s in subjects_input.split(",") if s.strip()]
days = [d.strip() for d in days_input.split(",") if d.strip()]

# Validation
if not subjects or not days or periods_per_day <= 0:
    print("Invalid input. Please try again.")
else:
    # Generate Timetable
    timetable = {day: random.choices(subjects, k=periods_per_day) for day in days}

    # Create DataFrame
    df = pd.DataFrame(timetable)
    # Fixed the f-string bracket syntax here
    df.index = [f"Period {i+1}" for i in range(periods_per_day)]

    print("\nTimetable Generated Successfully\n")
    print(df) # Using print() for standard terminal output

    # Save timetable
    df.to_csv("timetable.csv")
    print("\nTimetable saved as timetable.csv")